# Created with YamlCreate.ps1 v2.2.2 $debug=NVS1.CRLF.5-1-22621-963.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: bootandy.dust
PackageVersion: 0.8.4
InstallerType: zip
ReleaseDate: 2023-01-29
Installers:
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: dust-v0.8.4-i686-pc-windows-msvc/dust.exe
    PortableCommandAlias: dust.exe
  InstallerUrl: https://github.com/bootandy/dust/releases/download/v0.8.4/dust-v0.8.4-i686-pc-windows-msvc.zip
  InstallerSha256: C85718BA27327BE32EBA211E53D2F140169F2C009C8C352D143EE3EEB5FF11DC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: dust-v0.8.4-x86_64-pc-windows-msvc/dust.exe
    PortableCommandAlias: dust.exe
  InstallerUrl: https://github.com/bootandy/dust/releases/download/v0.8.4/dust-v0.8.4-x86_64-pc-windows-msvc.zip
  InstallerSha256: 13F52AC1E059D748FCC2AB99F926C50772BC30D741456452ADF9DC51918EE3AF
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.5.0
